paths: {
    data_src: "/home/dataset/kaggle/input/train_images/",
    data_dest: "/home/isaiah/kaggle/mammo/preprocessed/mammodata224.h5",
    metadata_src: "/home/dataset/kaggle/input/train.csv",
    metadata_dest: "/home/isaiah/kaggle/mammo/preprocessed/metadata.json",
    data_ids_dest: "/home/isaiah/kaggle/mammo/preprocessed/train_split.json",
    timesheet_dest: "/home/isaiah/kaggle/mammo/preprocessed/train_timesheet.json",
    model_load_src: "/home/isaiah/kaggle/mammo/results/20230208/densenet_best_02.pth",
    model_ckpts_dest: "/home/isaiah/kaggle/mammo/results/20230208/densenet_ckpt_03.pth",
    model_best_dest: "/home/isaiah/kaggle/mammo/results/20230208/densenet_best_03.pth",
    model_final_dest: "/home/isaiah/kaggle/mammo/results/20230208/densenet_final_03.pth",
    train_report_path: "/home/isaiah/kaggle/mammo/results/20230208/densenet_rep_03.csv"
}

preprocess_params: {
    file_extension: "h5",
    init_downsample_ratio: 2.5,
    resolution: [224, 224],
    normalization: True,
    test_set: False,
    num_samples: null,
    test_size: 0.25
}

metadata_params: {
    selected_columns: ['image_id', 'patient_id', 'laterality', 'view', 'age',
                       'cancer', 'implant', 'density', 'machine_id', 
                       'difficult_negative_case'],
    default_value: 'na',
    age_nan: "mean",
    laterality_map: {'L': 0, 'R': 1},
    view_map: {'CC': 0, 'MLO': 1},
    density_map: {'A': 1, 'B': 2, 'C': 3, 'D': 4},
    diff_neg_case_map: {FALSE: 0, TRUE: 1}
}

dataset_params: {
    augmentations: {"contrast_brightness"},
    labels: ["cancer"],
    sample_ratio: 0.5
}

optimizer_params: {
    lr: 3.0e-5    
}

scheduler_params: {
    base_lr: 1.0e-5,
    max_lr: 6.0e-5,
    step_size_up: 500,
    cycle_momentum: False
}

model_params: {
    growth_rate: 32,
    block_config: [6, 12, 64, 48],
    num_init_features: 64,
    bn_size: 4,
    drop_rate: 0,
    num_classes: 1,
    memory_efficient: False
}

run_params: {
    train: True,
    disable_cuda: False,
    epochs: 40,
    batch_size: 20,
    validation_size: 10,
    loss_weights: [1.],
    classes: ['cancer', 'healthy']
}
