paths: {
    data_src: "/home/isaiah/kaggle/mammo/train_images/",
    data_dest: "/home/isaiah/kaggle/mammo/preprocessed/mammodata224.h5",
    metadata_src: "/home/isaiah/kaggle/mammo/train.csv",
    metadata_dest: "/home/isaiah/kaggle/mammo/preprocessed/metadata.json",
    data_ids_dest: "/home/isaiah/kaggle/mammo/results/20230122/dummy_tests.json",
    timesheet_dest: "/home/isaiah/kaggle/mammo/preprocessed/train_timesheet.json",
    model_load_src: "/home/isaiah/kaggle/mammo/results/20230122/densenet_final_01.pth",
    model_ckpts_dest: "/home/isaiah/kaggle/mammo/results/20230207/densenet_ckpt_01.pth",
    model_final_dest: "/home/isaiah/kaggle/mammo/results/20230207/densenet_final_01.pth",
    train_report_path: "/home/isaiah/kaggle/mammo/results/20230207/densenet_rep_01.json",
    other_result_dest: "/home/isaiah/kaggle/mammo/results/20230207/other_results.csv",
    submission_path: "/home/isaiah/kaggle/mammo/results/20230207/submission.csv"
}

preprocess_params: {
    file_extension: "h5",
    init_downsample_ratio: 2.5,
    resolution: [224, 224],
    normalization: True,
    test_set: False,
    num_samples: 1000,
    test_size: 0.25
}

metadata_params: {
    selected_columns: ['image_id', 'patient_id', 'laterality', 'view', 'age',
                       'cancer', 'implant', 'density', 'machine_id', 
                       'difficult_negative_case'],
    default_value: 'na',
    age_nan: "mean",
    laterality_map: {'L': 0, 'R': 1},
    view_map: {'CC': 0, 'MLO': 1},
    density_map: {'A': 1, 'B': 2, 'C': 3, 'D': 4},
    diff_neg_case_map: {FALSE: 0, TRUE: 1}
}

dataset_params: {
    augmentations: {"contrast_brightness"},
    labels: ["patient_id", "laterality", "view", "cancer", "implant", "density", "age"] 
}

optimizer_params: {
    lr: 3.0e-5    
}

model_params: {
    growth_rate: 32,
    block_config: [6, 12, 24, 16],
    num_init_features: 64,
    bn_size: 4,
    drop_rate: 0,
    num_classes: 6,
    memory_efficient: False
}

run_params: {
    submission: False,
    train: False,
    disable_cuda: False,
    dataset: "balanced_cancer",
    epochs: 3,
    batch_size: 2,
    validation_size: 2,
    default_value: 'na',
    laterality_map: {1: 'L', 0: 'R'},
    loss_weights: [0.1, 0.2, 0.45, 0.05, 0.1, 0.1]
}
