paths: {
    data_src: "/home/dataset/kaggle/test_images/",
    data_dest: "/home/isaiah/kaggle/mammo/preprocessed/mammodata224.h5",
    metadata_src: "/home/dataset/kaggle/test.csv",
    metadata_dest: "/home/isaiah/kaggle/mammo/preprocessed/metadata.json",
    data_ids_dest: "/home/isaiah/kaggle/mammo/preprocessed/train_split.json",
    timesheet_dest: "/home/isaiah/kaggle/mammo/preprocessed/sub_timesheet.json",
    model_load_src: "/home/isaiah/kaggle/mammo/results/20230208/densenet_final_03.pth",
    submission_path: "/home/isaiah/kaggle/mammo/results/20230209/submission.csv",
    other_result_dest: "/home/isaiah/kaggle/mammo/results/20230209/other_res.csv"
}

preprocess_params: {
    file_extension: "h5",
    init_downsample_ratio: 2.5,
    resolution: [224, 224],
    normalization: True,
    test_set: True,
    num_samples: null,
    test_size: null
}

metadata_params: {
    selected_columns: ['image_id', 'patient_id', 'laterality', 'view'],
    default_value: 'na',
    laterality_map: {'L': 0, 'R': 1},
    view_map: {'CC': 0, 'MLO': 1}
}

dataset_params: {
    augmentations: {"contrast_brightness"},
    labels: ["patient_id", "laterality", "view"] 
}

model_params: {
    growth_rate: 32,
    block_config: [6, 12, 64, 48],
    num_init_features: 64,
    bn_size: 4,
    drop_rate: 0,
    num_classes: 1,
    memory_efficient: False
}

run_params: {
    submission: True,
    disable_cuda: False,
    batch_size: 1,
    loss_weights: [1.],
    default_value: 'na',
    laterality_map: {0: 'L', 1: 'R'},
    view_map: {0: 'CC', 1: 'MLO'},
    dataset: 'val',
    classes: ['cancer', 'healthy']
}
